### ISSUE TITLE
[RFC] Query fetch by primary key

### ISSUE THREAD

**Issue by vladfaust** [vladfaust/core#1]
*Maybe* need a query method to fetch by a primary key.

### Currently:

ATM I use `Query(User).where(id: id)` and it seems to be simple enough.

### Possible variants:
- `Query(User)[id]` - it's a *handy* method, but it looks ugly
- `Query(User).find(id)` - it's quite *handy* and not so ugly but interferes logically with `where`
- `Query(User).by_pk(id)` - is ugly
- `Query(User).by_id(id)` or `Query(User).id(id)` - ugly and will involve `Model::Schema::CORE__PRIMARY_KEY_FIELD` constant. I don't want to use `Schema`'s constants in `Query`

Any comments?

**Comment by Brusalk** [comment]
Nice project! Looks awesome!

One of the things I like least about ActiveRecord is having a billion ways to do everything. `Query(User).where(id: id)` is logical and clear to me.

I'd just stick with the where syntax :) 2c

**Comment by vladfaust** [comment]
@Brusalk, thank you! :heart: 

> ActiveRecord is having a billion ways to do everything

Very nice point. Crystal philosophy says _"one method for one action"_, and I love it. 

However, there are `Query#last` and `Query#first` methods already. Are they odd? :thinking:

**Comment by Brusalk** [comment]
I kind of feel like they're alright as they're a helper for an action that would otherwise take multiple actions to build together, compared to find/where where it's a 1:1 swap. At least, that's my feeling on it 😄

**Comment by jackturnbull** [comment]
Just spotted the open PR that introduces the `Query(User)[id]` helper. One hang up that I have on using the array accessor for this is that it could be potentially confusing for ordered responses and possibly lead to an inconsistent implementation depending on context. Here's how I mean, given some users in the DB:

* `Query(User)[1]` - Returns the user with the ID of 1
* `Query(User).order_by(:first_name)[1]` - Returns the user of index 1 from the ordered array

Unless of course this would only be if it was the first action on the query.

In all honesty, my vote would be for `find`. For my money its a common enough use-case to warrant the extra method, rather than pulling the array and accessing the first item each time you want to get a single user by ID, although I can definitely see all points of view.

**Comment by vladfaust** [comment]
@jackturnbull, `Repository#query` returns an array of Models, not a single one. Using `Query#find` may look like this:

```crystal
query = Query(User).find(42)
user = repo.query(query).first
```

However, it may be possible to add `Repository#query_one`...

**Comment by jackturnbull** [comment]
Okay I'm with you, got the accessors mixed up! The `[]` sytax seems much more reasonable in that case since I'd expect the find method to be on the repository itself (alongside insert, for example) rather than on the query.

Is there a reason that its going on the query rather than on the repository? Or is the goal not to overload the repository here?

Edit: I can see that this is about the query rather than the repository, but to provide a bit more context to my view on it; whenever I've got to write my own repository layer, I tend to refer to [the Hanami (pr. Lotus) model gem](https://github.com/hanami/model#repositories) for my personal de-facto list of methods that I implement - although it might be a little overkill for what you're doing with this lib!
